name: Deployment pipeline

# Map the repository variable (or workflow-level env) into env.CHECK_SKIP
env:
  CHECK_SKIP: ${{ vars.CHECK_SKIP }}

on:
  push:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
          node-version: '20'
       - name: Install dependencies 
         run: npm install --legacy-peer-deps 

       - name: lint
         run: npm run lint

       - name: e2etest
         run: |
          npm start &
          sleep 10
          cd playwright
          npm ci
          npx playwright install --with-deps
          npm test
      
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{github.ref == 'refs/heads/main' && github.event_name == 'push'}}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Trigger deployment:
    needs: [tag_release]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && ${{ env.CHECK_SKIP }} != 'true' }}
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  
    
